name: sap-data-generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - faker>=19.0.0
  - sqlite
  - pandas>=1.5.0
  - numpy>=1.24.0
  - jupyter>=1.0.0
  - ipython>=8.0.0
  - pip
  - pip:
    - python-dateutil
